# Site settings
title: 7om Tech
description: 'Crafting top-notch mobile experiences with over 10 years in Android and now in Flutter. Quality and innovation at the heart of every app journey.'
url: 'https://7omtech.fr'
baseurl: ''
google_analytics: 'G-7JSH88SKE0'
disqus_shortname: '7omtech'

author:
  name: 'Thomas Guerin'
  email: contact@7omtech.fr
  twitter_username: tom404_
  resume_url: "https://resume.7omtech.fr"
  github_username: tguerin
  linkedin_username: thomas-guerin-6233a76b

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-seo-tag', 'jekyll-sitemap']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
